[package]
name = "coreutils"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }

[[bin]]
name = "head"
path = "./head/main.rs"

[[bin]]
name = "tail"
path = "./tail/main.rs"
